name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Specify that the runner should use an Ubuntu VM
    
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up SSH to connect to EC2
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_KEY }}  # Use the private SSH key stored in GitHub Secrets

      # Step 3: SSH into EC2 and Deploy the Code
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@15.206.89.72 "
            cd /var/www/html && 
            git pull origin main && 
            sudo systemctl restart nginx
          "
